### ISSUE TITLE
Does not react to requests to set colors

### ISSUE THREAD

**Issue by dvpfig** [ChristopherRogers1991/mycroft-hue#14]
Hi, 

The skill works like a charm to turn lights on and off. And dim up and down. Also setting scenes work but not to setting colors. 
Is there a way to set the color e.g. to red or green or blue via a command?

**Comment by ChristopherRogers1991** [comment]
Hey @dvpfig,

This has not been implemented yet, however, there's no reason it can't be added. There are a few other things I need to implement first, but, I'll add this to the list, and see if I can get it knocked out (note that if you're a developer, you should feel free to make a pull request at any time).

Best,

Chris

**Comment by dvpfig** [comment]
thanks for the prompt reply. 
have been ages from my last proper program, so I will take some time to understand how this is done and how the skills work. I will give it a look but don't wait for it. 
this was a question on whether the function was in the skill. 
Now I know it is in the To Do List :)

Well done. 

Daniel

**Comment by estiens** [comment]
There's some functions here to turn hex codes and rgb values into hue approximations (I think it actually varies slightly by bulb type but don't nec need to go that far.)

https://github.com/bjohnso5/hue-hacking/blob/master/src/colors.js

There's a bunch of dicts online that have named colors and their hex values and/or rgb values, could just load that in and do the conversion

**Comment by alueck** [comment]
Hi,

I experimented a bit to allow color changes of the lights (https://github.com/alueck/mycroft-hue/commit/5d5ecaca4c5453141fad8f6da374bb3fa54b05dc). I ran into some issues, that I would like to discuss:

1. I added a field "color_mappings" to the settings for which a JSON string like "{ \"red\": [255,0,0], \"green\": [0,255,0] }" is expected. I would rather have this in a separate file, because it would be easier to read and you could support multiple languages by creating multipe files. I did try it with a separate file in the directory, where the __init__.py is located, but the file was not found on the read attempt.

2. The `change_color_intent` is currently missing the line `.require("Color")` and the handler currently does a hardcoded change to red (must exist in the "color_mappings" string in the settings.json). 
I register the colors similarily to the scenes and groups, but if I add the `.require("Color")`, the intent is not found anymore if I, for example, send "light color red" in the Mycroft CLI. If I leave this line out and just send "light color" to the Mycroft CLI, the intent is recognized and the hardcoded change to red is done.

I would appreciate some help with this issues @ChristopherRogers1991 and any other people that might have some more knowledge about Mycroft or Python.

**Comment by alueck** [comment]
I got it actually working now on my branch https://github.com/alueck/mycroft-hue/tree/feature/change-color

Now I just need more color definitions and I would like to reduce the redundancy in having to define the rgb values for each language. Gonna work a little bit on it and then probably open a pull request.
