### ISSUE TITLE
Document expected behaviour after install

### ISSUE THREAD

**Issue by gingerling** [ChristopherRogers1991/mycroft-hue#28]
Hi I am writing some docs for this skill but can't seem to get it working so far, I wonder, could you tell me the expected behavior following installation? Once it's installed, I have said "Hey Mycroft, turn off the lights" and he says he can't find the hue bridge. I am troubleshooting that now, but I am not actually sure what the process is supposed to be if he can find the bridge.

**Comment by ChristopherRogers1991** [comment]
Hello @gingerling,

When Mycroft can't find the bridge (the Phillips Hue hub) on your network, he should note that you can set the IP address manually. The easiest way to do that is via https://home.mycroft.ai/#/skill.

If you don't know the IP address of your router, you should be able to find it by logging into your router. The exact process for that will depend on your router.

-Chris

**Comment by gingerling** [comment]
Ok great, I will link you the docs shortly. If he can find the bridge, is the process

Install done
(nothing happens)
say "Hey Mycroft, turn on the lights"
He asks you to push the button on the bridge" etc?

**Comment by gingerling** [comment]
Hi, here you go:

http://www.gingerling.co.uk/setting-up-phillips-hue-on-mycroft-mark-1-including-guide-to-basic-ssh-access/

more to follow I am sure

**Comment by ChristopherRogers1991** [comment]
Hey @gingerling,

Apologies, I saw your previous comment but didn't have time to read the write up at the time, and forgot to circle back to it. It looks good and very thorough (I even learned it's possible to get to IP address of the hub via the Hue app, which is a great pro tip).

One note - you've titled the second block "Microsoft Hue" rather than "Mycroft Hue." Just thought I'd flag it.

Anyway, since this has been completed, I'm going to go ahead and close this out. Feel free to reach out in the future with any other questions or comments.

-Chris
